name: Stock and Crypto Bot

on:
  schedule:
    - cron: '0,30 * * * *'  # <-- 1-5를 삭제하고 *로 변경 (매일 30분마다 실행)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: 
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pandas pandas_ta FinanceDataReader requests pytz pyupbit  # <-- pyupbit 추가
          
      - name: Run bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
