name: Stock-Bot-Auto
on:
  schedule:
    - cron: '0,30 * * * *'
  workflow_dispatch: 
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        # Node 24 대응이 완료된 정확한 세부 버전을 사용합니다.
        uses: actions/checkout@v4.1.7 

      - name: Set up Python
        # Node 24 지원 패치가 끝난 버전을 명시합니다.
        uses: actions/setup-python@v5.1.1
        with:
          python-version: '3.11'

      - name: Install Libraries
        run: |
          python -m pip install --upgrade pip
          pip install finance-datareader pandas_ta python-telegram-bot pytz

      - name: Start Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
